import { ReactComponent as plus } from "./pplus.svg";
import { ReactComponent as breifcase } from "./briefcase.svg";
import { ReactComponent as chat } from "./chat.svg";
import { ReactComponent as checkbox } from "./checkbox.svg";
import { ReactComponent as close } from "./close.svg";
import { ReactComponent as contact } from "./contact.svg";
import { ReactComponent as downArr } from "./down-arr.svg";
import { ReactComponent as edit } from "./edit.svg";
import { ReactComponent as filter } from "./filter.svg";
import { ReactComponent as home } from "./home.svg";
import { ReactComponent as information } from "./information.svg";
import { ReactComponent as list } from "./list.svg";
import { ReactComponent as mail } from "./mail.svg";
import { ReactComponent as people } from "./people.svg";
import { ReactComponent as plusbg } from "./plus.svg";
import { ReactComponent as previous } from "./previous.svg";
import { ReactComponent as req } from "./req.svg";
import { ReactComponent as requirements } from "./requirements.svg";
import { ReactComponent as school } from "./school.svg";
import { ReactComponent as search } from "./search.svg";
import { ReactComponent as share } from "./share.svg";
import { ReactComponent as bell } from "./bell.svg";
import { ReactComponent as phone } from "./phone.svg";
import { ReactComponent as penedit } from "./penedit.svg";
import { ReactComponent as filter2 } from "./filter2.svg";
import { ReactComponent as lock } from "./lock.svg";
import { ReactComponent as tag } from "./tag.svg";
import { ReactComponent as linkedin } from "./linkedin.svg";

export const PlusIcon = plus;
export const BreifcaseIcon = breifcase;
export const ChatIcon = chat;
export const CheckboxIcon = checkbox;
export const CloseIcon = close;
export const ContactIcon = contact;
export const DownArrIcon = downArr;
export const EditIcon = edit;
export const FilterIcon = filter;
export const HomeIcon = home;
export const InformationIcon = information;
export const ListIcon = list;
export const MailIcon = mail;
export const PeopleIcon = people;
export const PlusBgIcon = plusbg;
export const PreviousIcon = previous;
export const ReqIcon = req;
export const RequirementsIcon = requirements;
export const SchoolIcon = school;
export const SearchIcon = search;
export const ShareIcon = share;
export const BellIcon = bell;
export const PhoneIcon = phone;
export const PenEditIcon = penedit;
export const Filter2Icon = filter2;
export const LockIcon = lock;
export const TagIcon = tag;
export const LinkedinIcon = linkedin;
